runtime: php82
handlers:
  - url: /
    script: public/index.php

env_variables:
  APP_STORAGE: /tmp # Important for App Engine
  CACHE_DRIVER: file
  SESSION_DRIVER: file

  DB_CONNECTION: mysql
  DB_HOST: plantaskr-445021:europe-central2:plantaskr # Format: PROJECT_ID:REGION:INSTANCE_NAME
  DB_PORT: 3306
  DB_DATABASE: plantaskr
  DB_USERNAME: plantaskr_user
  DB_PASSWORD: Iz-):@|iXQT;@qiu

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic


