runtime: php82
handlers:
  - url: /
    script: public/index.php

env_variables:
  APP_STORAGE: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
