name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, tokenizer, gd, mysql, zip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Publish Livewire Assets
        run: php artisan vendor:publish --tag=livewire:assets --force

      - name: Install npm dependencies
        run: npm ci

      - name: Run Mix
        run: npm run build

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set Environment Variables
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=plantaskr" >> .env
          echo "DB_USERNAME=plantaskr_user" >> .env
          echo "DB_HOST=plantaskr-445021:europe-central2:plantaskr" >> .env
          echo "DB_CONNECTION=mysql" >> .env


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}


      - name: Deploy to App Engine
        run: gcloud app deploy --version=v1 --promote --env-from-file=.env

      - name: Wait for App Engine instance to start
        run: |
          MAX_RETRIES=10
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            INSTANCE_STATUS=$(gcloud app instances list --format="value(vmStatus)" --filter="version.id=v1")
            if [[ "$INSTANCE_STATUS" == "RUNNING" ]]; then
              echo "Instance is running."
              break
            fi
            echo "Waiting for instance to start... (Attempt $i/$MAX_RETRIES)"
            sleep $RETRY_DELAY
          done
          if [[ "$INSTANCE_STATUS" != "RUNNING" ]]; then
            echo "Error: Instance did not start within the timeout period."
            exit 1
          fi

      - name: Run Artisan Migrations
        run: gcloud app instances ssh --service=default --version=v1 --command="php artisan migrate --force || exit 1"

      - name: Clear Cache (On App Engine Instance)
        run: gcloud app instances ssh --service=default --version=v1 --command="php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan route:clear"
