name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, tokenizer, gd, mysql, zip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or your preferred Node.js version

      - name: Install npm dependencies
        run: npm ci # or npm install

      - name: Run Mix (or other build process)
        run: npm run build # Or npm run production if you use that

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set APP_KEY from github secrets
        run: echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

        #database env vars
      - name: Set DB_PASSWORD from github secrets
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      - name: Set DB_DATABASE env var
        run: echo "DB_DATABASE=laravel_db" >> .env
      - name: Set DB_USERNAME env var
        run: echo "DB_USERNAME=laravel_user" >> .env
      - name: Set DB_HOST env var
        run: echo "DB_HOST=YOUR_CLOUD_SQL_CONNECTION_NAME" >> .env
      - name: Set DB_CONNECTION env var
        run: echo "DB_CONNECTION=mysql" >> .env

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Deploy to App Engine
        run: gcloud app deploy --version=v1 --promote

      - name: Wait for App Engine instance to start
        run: sleep 5 # Wait for 5 seconds. Adjust as needed.

      - name: Run Artisan Migrations
        run: gcloud app instances ssh --service=default --version=v1 --command="php artisan migrate --force || exit 1"
